Issue24 テストコードの追加
vviilloovv/books-app pull request #25
Opened 2020-04-22 05:11 UTC by vviilloovv

テストコードを作成する

2020-04-24 11:58 UTC, komagata requested changes

2020-04-24 11:58 UTC, komagata commented on .gitignore
> +/db/test.sqlite3-0
並列数によってもっと増えるのでそれに対応した書き方がいいかもです。

2020-04-24 11:58 UTC, komagata commented on test/models/user_test.rb
> +  def setup
```suggestion
 setup do
```

2020-04-27 09:49 UTC, vviilloovv commented on .gitignore
> +/db/test.sqlite3-0
sqlite-*に修正しました。

2020-04-27 09:50 UTC, vviilloovv commented on test/models/user_test.rb
> +  def setup
全ての`setup`メソッドの宣言方法を修正しました。

2020-04-27 11:29 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-04-27 13:15 UTC, merged